### ISSUE TITLE
labels mixup on Windows in extract_features.py

### ISSUE THREAD

**Issue by christophfink** [DigitalGeographyLab/MilVehicles#1]
Since on Windows os.sep is a backslash, but paths for this script might (legitimately) be specified with a forward slash, line 108 of `extract_features.py` returns a different (wrong) set of labels as lines 99f. 

(fix is easy, I’m preparing a pull request)

**Comment by thiippal** [comment]
Fixed in [68372e2](https://github.com/DigitalGeographyLab/MilVehicles/commit/68372e2e5499bcd21b70e304abedc667769381cb).

**Comment by christophfink** [comment]
sorry for the mix-up – in my test environment I had `subdirs` of the `os.walk` renamed to `dirpath` – bad copy and pasting :/
You could use `subdirs` directly, without deriving it from `path`
